# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{role_play}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Krzysztof Zylawy", "Mint Digital"]
  s.date = %q{2009-12-04}
  s.email = %q{philnash@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "Manifest",
     "README",
     "Rakefile",
     "VERSION",
     "generators/has_roles/USAGE",
     "generators/has_roles/has_roles_generator.rb",
     "generators/has_roles/templates/migration.rb",
     "has_roles.gemspec",
     "install.rb",
     "lib/has_roles.rb",
     "lib/role.rb",
     "lib/role_assignment.rb",
     "rails/init.rb",
     "tasks/has_roles_tasks.rake",
     "test/assertions.rb",
     "test/has_roles_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/mintdigital/has_roles}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple roles for ActiveRecord}
  s.test_files = [
    "test/assertions.rb",
     "test/has_roles_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

